name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build the web application
        run: |
          cd sample-web-app
          mvn clean package

      - name: Deploy to Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TOMCAT_SERVER_HOST }}  
          username: ${{ secrets.TOMCAT_SERVER_USERNAME }}  
          password: ${{ secrets.TOMCAT_SERVER_PASSWORD }} 
          script: |
            cd sample-web-app/target
            # Assuming your .war file is named "sample-web-app.war"
            scp sample-web-app.war ${{ secrets.TOMCAT_SERVER_USERNAME }}@${{ secrets.TOMCAT_SERVER_HOST }}:/path/to/tomcat/webapps

      - name: Restart Tomcat
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TOMCAT_SERVER_HOST }}
          username: ${{ secrets.TOMCAT_SERVER_USERNAME }}
          password: ${{ secrets.TOMCAT_SERVER_PASSWORD }}
          script: |
            # Replace "tomcat-service" with the actual name of the Tomcat service on your server.
            sudo systemctl restart tomcat-service
